name = "ShopLLMZ"
client_id = "98ecd3968dbbddd9b0a80eae8c630dee"
application_url = "https://www.shopllmz.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_products,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://www.shopllmz.com/api/auth/callback",
  "https://www.shopllmz.com/api/auth"
]

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks/app/uninstalled"


  [webhooks.privacy_compliance]
  customer_deletion_url = "https://www.shopllmz.com/api/webhooks/customers/redact"
  customer_data_request_url = "https://www.shopllmz.com/api/webhooks/customers/data_request"
  shop_deletion_url = "https://www.shopllmz.com/api/webhooks/shop/redact"
[pos]
embedded = false
